version: '3.9'

services:
    front:
        container_name: front
        build:
            context: .
            dockerfile: infrastructures/front-c/Dockerfile
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
        env_file:
            - .env
        volumes:
            - ./src/services/front-c/:/src/app/
        networks:
            - cluster-c-network
        restart: always


    backend:
        container_name: backend
        build:
            context: .
            dockerfile: infrastructures/backend/Dockerfile
        ports:
            - "9000:9000"
        environment:
            - PORT=9000
            - ENVIRONMENT_DEBUG=1
        env_file:
            - .env
        volumes:
            - ./src/services/backend/:/src/app/
            - shared-workspace:/opt/workspace
        networks:
            - spark-net
            - cluster-c-network
        restart: always


volumes:
    shared-workspace:
        external: true
        name: pres3-spark_shared-workspace

networks:
    spark-net:
        external: true
    cluster-c-network:



